name: Interim
version: dev-0.2.11
main: org.r7l.interim.Interim
api-version: '1.21'
description: A comprehensive nations, towns, and claiming plugin
author: r7l-labs
softdepend: [Vault, BlueMap, floodgate, PlaceholderAPI]

commands:
  interim:
    description: Open the Interim overview GUI
    usage: /<command>
    aliases: [la, to, town]
  menu:
    description: Open the main Interim menu GUI
    usage: /<command>
    aliases: [gui, tmenu]
  town:
    description: Town management commands
    usage: /<command> [args]
    aliases: [t]
  nation:
    description: Nation management commands
    usage: /<command> [args]
    aliases: [n]
  plot:
    description: Plot management commands
    usage: /<command> [args]
    aliases: [p]
  interimadmin:
    description: Administrative commands for Interim
    usage: /<command> [args]
    aliases: [tadmin]
    permission: interim.admin
  map:
    description: Open the interactive claim map
    usage: /<command>
    aliases: [claimmap, cmap]

permissions:
  interim.admin:
    description: Admin permissions for Interim
    default: op
  interim.town.create:
    description: Allow creating towns
    default: true
  interim.nation.create:
    description: Allow creating nations
    default: true
  interim.war:
    description: Access to the war system (declaring war, viewing wars)
    default: false
